name: push-hook
on:
  push:
    branches: [ master ] #master branchì˜ ì´ë²¤íŠ¸ì— ëŒ€í•´ì„œë§Œ í›… ë‚ ë¦¼

jobs:
  send:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'log')" # commit messageì— ğŸ“ ì•„ì´ì½˜ì´ í¬í•¨ëœ ê²½ìš°ì—ë§Œ í›… ë‚ ë¦¼
    steps:
    - name: curl
      env:
        #hook_url: https://hook.dooray.com/services/1387695619080878080/2415136738665337382/81Xs8epCQbyHyTrHRIXxQQ # TEST ìš©
        hook_url: https://hook.dooray.com/services/1387695619080878080/2768245954096979957/N6FqbzwAQ7KxaCTS6AseWw
      run: curl -H "Content-Type:application/json" -X POST -d '{"botName":"100ì¼-ë…ì„œ-ë´‡", "botIconImage":"https://i.ibb.co/cXY9K3L/image4.png", "text":"ğŸ‰ ${{github.actor}} pushed! `${{github.event.head_commit.message}}` [â¥](${{github.event.head_commit.url}})"}' $hook_url
      
